const { initializeApp } = require("firebase/app");
const { getFirestore, doc, getDoc } = require("firebase/firestore");
const { getAuth, signInWithEmailAndPassword } = require("firebase/auth");
const https = require("https");
const fs = require("fs");
const path = require("path");

const firebaseConfig = {
  apiKey: "AIzaSyDksEsBF9Nyq94OjJ-rkW9HlfMQ0gEHnrw",
  authDomain: "traderkishann-e33ff.firebaseapp.com",
  projectId: "traderkishann-e33ff",
  storageBucket: "traderkishann-e33ff.firebasestorage.app",
  messagingSenderId: "228433487881",
  appId: "1:228433487881:web:5a30a8403ffa72370e30d8"
};

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);

const GEMINI_API_KEY = process.env.GEMINI_API_KEY || "";

async function run() {
  const email = process.argv[2] || "trader@gmail.com";
  const password = process.argv[3] || "password";

  console.log(`[1/4] Authenticating ${email}...`);
  try {
    const userCredential = await signInWithEmailAndPassword(auth, email, password);
    const user = userCredential.user;
    
    console.log(`[2/4] Fetching trading journal from Firestore...`);
    const userDocRef = doc(db, "users", user.uid);
    const userDocSnap = await getDoc(userDocRef);

    if (!userDocSnap.exists()) {
      console.error("Error: User document not found in Firestore.");
      process.exit(1);
    }

    const userData = userDocSnap.data();
    const trades = userData.trades || [];
    console.log(`Loaded ${trades.length} trades.`);

    if (trades.length === 0) {
      console.log("No trades found to analyze.");
      process.exit(0);
    }

    console.log(`[3/4] Sending data to Gemini AI for Deep Quant & Psychological Analysis...`);

    const promptText = `
You are an Elite Financial Quant Analyst, Risk Manager, Performance Coach, and Trading Psychologist with institutional-level expertise.

Your task is to perform a deep statistical and behavioral analysis of the user's complete trading journal.

Here is the user's complete trading data in JSON format:
${JSON.stringify(trades, null, 2)}

OBJECTIVE:
Identify hidden patterns, strengths, weaknesses, risk-management flaws, emotional triggers, and statistically significant trading opportunities that can improve long-term profitability.

IMPORTANT RULES:
1. Base conclusions ONLY on actual journal data.
2. Do not make assumptions without evidence.
3. Highlight confidence levels for every conclusion.
4. Focus on statistical significance, not random observations.
5. If data is insufficient for a conclusion, explicitly state so.
6. Prioritize actionable insights over generic advice.

Please provide the final report structured exactly in these sections:
SECTION 1: EXECUTIVE SUMMARY
SECTION 2: TIME & DAY ANALYSIS
SECTION 3: ACCURACY & WIN-RATE ANALYSIS
SECTION 4: RISK MANAGEMENT AUDIT
SECTION 5: BEHAVIORAL & PSYCHOLOGICAL ANALYSIS
SECTION 6: ADVANCED QUANT ANALYSIS
SECTION 7: CONSTRUCTIVE ACTION PLAN

TOP 5 CHANGES THAT WOULD MOST IMPROVE THIS TRADER'S PROFITABILITY (rank from highest to lowest impact).
`;

    const requestBody = JSON.stringify({
      contents: [
        {
          parts: [
            {
              text: promptText
            }
          ]
        }
      ]
    });

    const options = {
      hostname: 'generativelanguage.googleapis.com',
      port: 443,
      path: `/v1beta/models/gemini-2.5-flash:generateContent?key=${GEMINI_API_KEY}`,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(requestBody)
      }
    };

    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', (chunk) => {
        data += chunk;
      });

      res.on('end', () => {
        try {
          const responseJson = JSON.parse(data);
          if (responseJson.candidates && responseJson.candidates[0].content.parts[0].text) {
            const analysisReport = responseJson.candidates[0].content.parts[0].text;
            console.log("\n[4/4] Analysis successfully generated by Gemini!");
            
            const outputPath = path.join(__dirname, "quant_analysis_report.md");
            fs.writeFileSync(outputPath, analysisReport, 'utf8');
            console.log(`Saved report to: ${outputPath}\n`);
            
            console.log("==================================================");
            console.log(analysisReport);
            console.log("==================================================");
            process.exit(0);
          } else {
            console.error("Error: Unexpected API response format:", JSON.stringify(responseJson));
            process.exit(1);
          }
        } catch (e) {
          console.error("Error parsing Gemini response JSON:", e);
          console.log("Raw Response received:", data);
          process.exit(1);
        }
      });
    });

    req.on('error', (e) => {
      console.error(`Gemini request failed: ${e.message}`);
      process.exit(1);
    });

    req.write(requestBody);
    req.end();

  } catch (error) {
    console.error("Execution failed:", error.message || error);
    process.exit(1);
  }
}

run();
